version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: ai-mock-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: interviews
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: ai-mock-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

volumes:
  mongo_data:
